# Generated by Django 4.0.3 on 2022-04-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plaid_access_token',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
